### ISSUE TITLE
the script does not work, here is the output:

### ISSUE THREAD

**Issue by levitki** [RobsRepo/Collecting-Okta-Event-Logs#2]
OKTA Events Script LOCKED 2020-05-14 15:54:34.439284
OKTA Events Script UNLOCKED 2020-05-14 15:54:35.272416
Traceback (most recent call last):
  File "oktaEvents.py", line 87, in <module>
    main()
  File "oktaEvents.py", line 17, in main
    runit(org,token,restRecordLimit)
  File "oktaEvents.py", line 23, in runit
    jsonData = getDataFromEndPoint(org,token,getStartTime(),restRecordLimit)
  File "oktaEvents.py", line 35, in getDataFromEndPoint
    response = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 410: Gone

**Comment by 0ccupi3R** [comment]
Please sue the correct URL for Okta. i.e. `https://' + org + '.okta.com/api/v1/logs'`
